### PR TITLE
[minor] support goodreads CSV

### PR DESCRIPTION
**Pull request by camjc**
Haven't been able to get the project running locally yet, so haven't tested this.
I hope its close-to-ready, and I'll try again sometime to get the project running so I can test, but if you'd like to build it yourself and test that'd be great. Happy to make any changes suitable, and let me know if you need an example goodreads CSV. Thanks again.

### CODE REVIEW

**Comment by AndrewBennet** [comment]
Thanks for this! I'll try to look at it closer soon.

**Comment by camjc** [comment]
@AndrewBennet Anything I can do to help this along?

**Comment by AndrewBennet** [comment]
Sorry for taking so long to get to this! I've not had very much time recently to work on the app - I'll try to get this in to the next release though. Thanks again for the contribution.

**Comment by camjc** [comment]
Thanks for the merge :)

**Pull request merged**
